In [1]:
import torch

In [2]:
#x=torch.randn(3, requires_grad=True)

In [3]:
x

tensor([-0.7857, -1.5373,  1.6843], requires_grad=True)

In [4]:
#y=x+2

In [5]:
y

tensor([1.2143, 0.4627, 3.6843], grad_fn=<AddBackward0>)

In [6]:
#z=y*y*2

In [7]:
#z=z.mean()

In [8]:
z

tensor(10.1750, grad_fn=<MeanBackward0>)

In [9]:
#z.backward()

In [10]:
#x.grad

tensor([1.6190, 0.6169, 4.9124])

In [11]:
#x=torch.randn(3, requires_grad=False)

In [12]:
x

tensor([-0.6661,  0.0834,  1.0074])

In [13]:
#y=x+2

In [14]:
y

tensor([1.3339, 2.0834, 3.0074])

In [15]:
#z=y*y*2

In [16]:
#z=z.mean()

In [17]:
z

tensor(10.1097)

In [18]:
#z.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [19]:
#x=torch.randn(3, requires_grad=True)

In [20]:
x

tensor([ 1.3151,  0.5382, -0.1759], requires_grad=True)

In [21]:
#y=x+2

In [22]:
y

tensor([3.3151, 2.5382, 1.8241], grad_fn=<AddBackward0>)

In [23]:
#z=y*y*2

In [24]:
z

tensor([21.9793, 12.8847,  6.6545], grad_fn=<MulBackward0>)

In [37]:
#x=torch.randn(3, requires_grad=True)

In [38]:
x

tensor([ 0.9644, -0.9846,  0.8515], requires_grad=True)

In [39]:
#y=x+2

In [40]:
y

tensor([2.9644, 1.0154, 2.8515], grad_fn=<AddBackward0>)

In [41]:
#z=y*y*2

In [42]:
z

tensor([17.5754,  2.0619, 16.2621], grad_fn=<MulBackward0>)

In [43]:
#v=torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)

In [44]:
#z.backward(v)

In [48]:
#x.grad

tensor([1.1858, 4.0614, 0.0114])

In [49]:
#x=torch.randn(3, requires_grad=True)

In [50]:
x

tensor([ 0.1966, -0.0922,  1.2824], requires_grad=True)

In [51]:
#x.requires_grad_(False)

tensor([ 0.1966, -0.0922,  1.2824])

In [52]:
x

tensor([ 0.1966, -0.0922,  1.2824])

In [53]:
#x=torch.randn(3, requires_grad=True)

In [54]:
x

tensor([-1.4573,  1.0575, -0.5684], requires_grad=True)

In [55]:
#y=x.detach()

In [56]:
y

tensor([-1.4573,  1.0575, -0.5684])

In [57]:
#x=torch.randn(3, requires_grad=True)

In [58]:
x

tensor([ 2.2283, -1.2353, -0.6233], requires_grad=True)

In [59]:
#with torch.no_grad():
    #y=x+2
    #print(y)

tensor([4.2283, 0.7647, 1.3767])


In [60]:
#x=torch.randn(3, requires_grad=True)

In [61]:
x

tensor([0.5026, 0.9299, 0.5117], requires_grad=True)

In [62]:
#y=x+2

In [63]:
y

tensor([2.5026, 2.9299, 2.5117], grad_fn=<AddBackward0>)

In [64]:
#weights=torch.ones(4,requires_grad=True)

In [66]:
#for epoch in range(1):
    #model_output=(weights*3).sum()
    #model_output.backward()
    #print(weights.grad)

tensor([3., 3., 3., 3.])


In [68]:
#weights=torch.ones(4,requires_grad=True)

In [69]:
#for epoch in range(2):
    #model_output=(weights*3).sum()
    #model_output.backward()
    #print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])


In [72]:
#weights=torch.ones(4,requires_grad=True)

In [73]:
#for epoch in range(3):
    #model_output=(weights*3).sum()
    #model_output.backward()
    #print(weights.grad)
    #weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [75]:
#weights=torch.ones(4,requires_grad=True)

In [76]:
#optimizer=torch.optim.SGD(weights, lr=0.01)
#optimizer.step()
#optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor

In [77]:
weights=torch.ones(4,requires_grad=True)

In [78]:
z.backward()

RuntimeError: grad can be implicitly created only for scalar outputs